In [1]:
import numpy as np
npz = np.load('/home/e19b516g/yejing/data/data_for_graph/npz/val/form_5_648_E3236.npz')

In [3]:
print(npz['edge_labels'])

[[0. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
 [8. 0. 2. 0. 0. 0. 0. 0. 0. 0.]
 [0. 8. 0. 2. 2. 0. 0. 0. 0. 0.]
 [0. 0. 8. 0. 1. 2. 2. 2. 0. 0.]
 [0. 0. 8. 1. 0. 2. 2. 2. 0. 0.]
 [0. 0. 0. 8. 8. 0. 1. 1. 2. 2.]
 [0. 0. 0. 8. 8. 1. 0. 1. 2. 2.]
 [0. 0. 0. 8. 8. 1. 1. 0. 2. 2.]
 [0. 0. 0. 0. 0. 8. 8. 8. 0. 1.]
 [0. 0. 0. 0. 0. 8. 8. 8. 1. 0.]]


In [6]:
import torch
a = torch.tensor([[0,1],[1,0]])
# fill the diagonal with 1
a.fill_diagonal_(1)

tensor([[1, 1],
        [1, 1]])